Cam.create([
  {location: "Argyle Street near Yim Po Fong Street", latitude: 22.320046, longitude: 114.172688, uri: "http://tdcctv.data.one.gov.hk/K202F.JPG" },
{location: "Boundary Street near Tai Hang Tung Road", latitude: 22.326854, longitude: 114.172184, uri: "http://tdcctv.data.one.gov.hk/K209F.JPG" },
{location: "Canton Road / Salisbury Road", latitude: 22.294665, longitude: 114.169641, uri: "http://tdcctv.data.one.gov.hk/K121F.JPG" },
{location: "Canton Road near China HK City", latitude: 22.301644, longitude: 114.168107, uri: "http://tdcctv.data.one.gov.hk/K104F.JPG" },
{location: "Chatham Road near Austin Road", latitude: 22.303153, longitude: 114.177055, uri: "http://tdcctv.data.one.gov.hk/K106F.JPG" },
{location: "Chatham Road near Princess Margaret Road", latitude: 22.306458, longitude: 114.180005, uri: "http://tdcctv.data.one.gov.hk/K109F.JPG" },
{location: "Cherry Street near Hoi Wang Road", latitude: 22.318597, longitude: 114.163344, uri: "http://tdcctv.data.one.gov.hk/K221F.JPG" },
{location: "Cheung Sha Wan Road near Kwong Cheung Street", latitude: 22.338863, longitude: 114.151885, uri: "http://tdcctv.data.one.gov.hk/K305F.JPG" },
{location: "Ching Cheung Road near Caritas Medical Centre", latitude: 22.342068, longitude: 114.153076, uri: "http://tdcctv.data.one.gov.hk/K802F.JPG" },
{location: "Chui Ling Road near Po Shun Road", latitude: 22.305793, longitude: 114.255612, uri: "http://tdcctv.data.one.gov.hk/TK110F.JPG" },
{location: "Clear Water Bay Road near Fei Ngo Shan Road", latitude: 22.334357, longitude: 114.225088, uri: "http://tdcctv.data.one.gov.hk/K627F.JPG" },
{location: "Cross Harbour Tunnel Kowloon Side", latitude: 22.30356, longitude: 114.180805, uri: "http://tdcctv.data.one.gov.hk/K107F.JPG" },
{location: "Eastern Harbour Crossing Kowloon Side", latitude: 22.300597, longitude: 114.232899, uri: "http://tdcctv.data.one.gov.hk/K952F.JPG" },
{location: "Jordan Road near Ferry Street", latitude: 22.306259, longitude: 114.16712, uri: "http://tdcctv.data.one.gov.hk/K108F.JPG" },
{location: "Kai Cheung Road near Wang Chiu Road", latitude: 22.325693, longitude: 114.208641, uri: "http://tdcctv.data.one.gov.hk/K613F.JPG" },
{location: "Kai Tak Tunnel Kowloon City Side", latitude: 22.320498, longitude: 114.190175, uri: "http://tdcctv.data.one.gov.hk/K404F.JPG" },
{location: "Kwai Chung Road near Mei Foo Sun Chuen", latitude: 22.359006, longitude: 114.130621, uri: "http://tdcctv.data.one.gov.hk/K325F.JPG" },
{location: "Kwun Tong Bypass near Kai Cheung Road ", latitude: 22.325068, longitude: 114.204274, uri: "http://tdcctv.data.one.gov.hk/K814F.JPG" },
{location: "Kwun Tong Bypass near Laguna City", latitude: 22.308433, longitude: 114.227717, uri: "http://tdcctv.data.one.gov.hk/K812F.JPG" },
{location: "Kwun Tong Bypass near Lai Yip Street", latitude: 22.313148, longitude: 114.216441, uri: "http://tdcctv.data.one.gov.hk/K813F.JPG" },
{location: "Kwun Tong Road near Kai Yip Estate", latitude: 22.329137, longitude: 114.211602, uri: "http://tdcctv.data.one.gov.hk/K621F.JPG" },
{location: "Kwun Tong Road near Kowloon Bay MTR Station", latitude: 22.322875, longitude: 114.214456, uri: "http://tdcctv.data.one.gov.hk/K809F2.JPG" },
{location: "Kwun Tong Road near Ngau Tau Kok MTR Station", latitude: 22.315302, longitude: 114.218726, uri: "http://tdcctv.data.one.gov.hk/K810F.JPG" },
{location: "Lei Yue Mun Road near Cha Kwo Ling Road", latitude: 22.309193, longitude: 114.230979, uri: "http://tdcctv.data.one.gov.hk/K602F.JPG" },
{location: "Lung Cheung Road near Chak On Estate", latitude: 22.342008, longitude: 114.164942, uri: "http://tdcctv.data.one.gov.hk/K804F.JPG" },
{location: "Lung Cheung Road / Chuk Yuen Road", latitude: 22.34306, longitude: 114.184383, uri: "http://tdcctv.data.one.gov.hk/K505F.JPG" },
{location: "Lung Cheung Road / Clear Water Bay Road", latitude: 22.334496, longitude: 114.209143, uri: "http://tdcctv.data.one.gov.hk/K614F.JPG" },
{location: "Lung Cheung Road / Po Kong Village Road", latitude: 22.341462, longitude: 114.198457, uri: "http://tdcctv.data.one.gov.hk/K508F.JPG" },
{location: "Ma Tau Wai Road near Farm Road", latitude: 22.321187, longitude: 114.187505, uri: "http://tdcctv.data.one.gov.hk/K405F.JPG" },
{location: "Nathan Road near Lai Chi Kok Road", latitude: 22.322686, longitude: 114.168847, uri: "http://tdcctv.data.one.gov.hk/K205F.JPG" },
{location: "Po Lam Road North near Po Hong Road", latitude: 22.326318, longitude: 114.251223, uri: "http://tdcctv.data.one.gov.hk/TK101F.JPG" },
{location: "Po Shun Road near Tseung Kwan O Swimming Pool", latitude: 22.316503, longitude: 114.260525, uri: "http://tdcctv.data.one.gov.hk/TK105F.JPG" },
{location: "Prince Edward Rd W Flyover nr Olympic Garden", latitude: 22.32773, longitude: 114.190143, uri: "http://tdcctv.data.one.gov.hk/K506F.JPG" },
{location: "Prince Edward Road East near San Po Kong", latitude: 22.332035, longitude: 114.196014, uri: "http://tdcctv.data.one.gov.hk/K521F.JPG" },
{location: "Princess Margaret Road near King's Park", latitude: 22.310736, longitude: 114.177944, uri: "http://tdcctv.data.one.gov.hk/K123F.JPG" },
{location: "Princess Margaret Road / Argyle Street", latitude: 22.321495, longitude: 114.178235, uri: "http://tdcctv.data.one.gov.hk/K409F.JPG" },
{location: "Princess Margaret Road / Pui Ching Road", latitude: 22.317436, longitude: 114.178525, uri: "http://tdcctv.data.one.gov.hk/K408F.JPG" },
{location: "Salisbury Road near Chatham Road", latitude: 22.295489, longitude: 114.175253, uri: "http://tdcctv.data.one.gov.hk/K102F.JPG" },
{location: "Salisbury Road near Nathan Road", latitude: 22.294795, longitude: 114.17227, uri: "http://tdcctv.data.one.gov.hk/K101F.JPG" },
{location: "Sau Mau Ping Road near Hip Wo Street", latitude: 22.324006, longitude: 114.225957, uri: "http://tdcctv.data.one.gov.hk/K607F.JPG" },
{location: "Tate's Cairn Tunnel Kowloon Side", latitude: 22.341204, longitude: 114.204231, uri: "http://tdcctv.data.one.gov.hk/K931F.JPG" },
{location: "Tseung Kwan O Road near Tsui Ping South Estate", latitude: 22.311729, longitude: 114.233703, uri: "http://tdcctv.data.one.gov.hk/K811F.JPG" },
{location: "Tseung Kwan O Tunnel - Tseung Kwan O Side", latitude: 22.321187, longitude: 114.250869, uri: "http://tdcctv.data.one.gov.hk/TK904F.JPG" },
{location: "Waterloo Road / Ferry Street", latitude: 22.312473, longitude: 114.167454, uri: "http://tdcctv.data.one.gov.hk/K111F.JPG" },
{location: "Waterloo Road near Tung Fong Street", latitude: 22.313168, longitude: 114.171347, uri: "http://tdcctv.data.one.gov.hk/K112F.JPG" },
{location: "Waterloo Road / Cornwall Street", latitude: 22.339944, longitude: 114.179287, uri: "http://tdcctv.data.one.gov.hk/K502F.JPG" },
{location: "West Kowloon Corridor near Nam Cheong Estate", latitude: 22.324482, longitude: 114.155404, uri: "http://tdcctv.data.one.gov.hk/K816F.JPG" },
{location: "West Kowloon Highway near Lai Wan Interchange", latitude: 22.3313, longitude: 114.143912, uri: "http://tdcctv.data.one.gov.hk/K914F.JPG" },
{location: "West Kowloon Hwy - Yau Ma Tei Interchange N ", latitude: 22.313714, longitude: 114.161314, uri: "http://tdcctv.data.one.gov.hk/K911F.JPG" },
{location: "Western Harbour Crossing Kowloon Side", latitude: 22.302686, longitude: 114.157979, uri: "http://tdcctv.data.one.gov.hk/K901F.JPG" },
{location: "Aberdeen Praya Road near Fish Market ", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H429F.JPG" },
{location: "Aberdeen Tunnel - Aberdeen Side ", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H421F.JPG" },
{location: "Aberdeen Tunnel - Wan Chai Side ", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H210F.JPG" },
{location: "Ap Lei Chau Bridge Road near Aberdeen Police Station ", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H422F2.JPG" },
{location: "Canal Road Flyover near Gloucester Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H904F.JPG" },
{location: "Canal Road Flyover near Times Square ", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H216F.JPG" },
{location: "Causeway Road near Hing Fat Street", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H305F.JPG" },
{location: "Connaught Road Central near Exchange Square", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H106F.JPG" },
{location: "Connaught Road Central near Shun Tak Centre", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H110F.JPG" },
{location: "Connaught Road West", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H703F.JPG" },
{location: "Cotton Tree Drive near Murray Building", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H138F.JPG" },
{location: "Cross Harbour Tunnel Hong Kong Side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H207F.JPG" },
{location: "Fleming Road near Harbour Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H204F.JPG" },
{location: "Gloucester Road near Sun Hung Kai Center", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H222F.JPG" },
{location: "Gloucester Road near Wan Chai Interchange", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H215F.JPG" },
{location: "Harcourt Road near Red Cross Headquarter", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H214F.JPG" },
{location: "Hennessy Road near Arsenal Street", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H201F.JPG" },
{location: "Island Eastern Corridor near Hoi Yu Street", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H802F.JPG" },
{location: "Island Eastern Corridor near Ka Wah Centre", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H801F.JPG" },
{location: "Island Eastern Corridor near Quarry Bay Park", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H803F.JPG" },
{location: "King's Road near Tin Chong Street", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H307F.JPG" },
{location: "Morrison Hill Road near Sports Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H903F.JPG" },
{location: "Pedder Street", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H107F.JPG" },
{location: "Pok Fu Lam Road near Pokfield Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H130F.JPG" },
{location: "Pok Fu Lam Road near Smithfield Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H132F2.JPG" },
{location: "Queen's Road Central near Garden Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H109F.JPG" },
{location: "Queen's Road Central near Ice House Street", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H108F.JPG" },
{location: "Queen's Road East near Stubbs Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H209F.JPG" },
{location: "Western Harbour Crossing Hong Kong Side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H702F.JPG" },
{location: "Wong Chuk Hang Road near Aberdeen Technical School", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H422F1.JPG" },
{location: "Wong Chuk Hang Road near Aberdeen Tunnel", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H401F.JPG" },
{location: "Yee Wo Street near Hennessy Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/H203F.JPG" },
{location: "Castle Peak Road near Texaco Road North", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW117F.JPG" },
{location: "Castle Peak Road near Wo Yi Hop Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW109F.JPG" },
{location: "Cheung Pei Shan Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SM936F.JPG" },
{location: "Cheung Pei Shan Road near Mei Wan Street", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW701F.JPG" },
{location: "Cheung Tsing Bridge", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TC101F.JPG" },
{location: "Cheung Tsing Highway near Kam Chuk Kok", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TC302F.JPG" },
{location: "Kwai Chung Road near Container Terminal", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW102F.JPG" },
{location: "Kwai Chung Road near Kwai Hing MTR Station", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW108F.JPG" },
{location: "Kwai Tsing Road near Tsing Yi Bridge", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW105F.JPG" },
{location: "Nam Wan Tunnel - Sai Tso Wan Side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TS101F.JPG" },
{location: "Nam Wan Tunnel - Stonecutters Bridge side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TS102F.JPG" },
{location: "Texaco Road Flyover near Sha Tsui Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW116F.JPG" },
{location: "Tsing Kwai Highway Near Container Port 4", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TC104F.JPG" },
{location: "Tsing Kwai Highway/Cheung Tsing Tunnel", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW121F.JPG" },
{location: "Tsing Sha Highway near Lai Chi Kok", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TS104F.JPG" },
{location: "Tsuen Wan Road near Tai Chung Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW120F.JPG" },
{location: "Tsuen Wan Road near Tsuen Tsing Interchange", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW103F.JPG" },
{location: "Wo Yi Hop Road near Lei Shu Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TW112F.JPG" },
{location: "Castle Peak Road near Hung Shui Kiu", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TI101F.JPG" },
{location: "Castle Peak Road near Pok Oi Interchange", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/YL111F.JPG" },
{location: "Castle Peak Road near Yuen Long", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/YL106F.JPG" },
{location: "Kong Sham Western Highway near Ha Tsuen", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SW103F.JPG" },
{location: "Long Tin Road near Long Ping Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/YL101F.JPG" },
{location: "Lung Mun Road near Tuen Mun Recreation and Sports Centre", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TM103F.JPG" },
{location: "Lung Mun Road near Wu Chui Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/RT115F.JPG" },
{location: "Pui To Road near Tuen Mun Park", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TM118F.JPG" },
{location: "Ting Kau Bridge", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TC604F.JPG" },
{location: "Tuen Mun Road - Chai Wan Kok", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR101F.JPG" },
{location: "Tuen Mun Road - near Tsing Lung Tau", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR111F.JPG" },
{location: "Tuen Mun Road - Sam Shing Hui", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR119F.JPG" },
{location: "Tuen Mun Road - Sham Tseng Interchange", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR108F.JPG" },
{location: "Tuen Mun Road - Sham Tseng Section", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR107F.JPG" },
{location: "Tuen Mun Road - Siu Lam Section", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR116F.JPG" },
{location: "Tuen Mun Road - Tai Lam Kok Section", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR114F.JPG" },
{location: "Tuen Mun Road - Ting Kau Section", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR105F.JPG" },
{location: "Tuen Mun Road - Yau Kom Tau Section", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR103F.JPG" },
{location: "Tsuen Mun Road - near MTR Siu Hong Station", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR706F.JPG" },
{location: "Tuen Mun Road near Tsing Yin Street", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TR704F.JPG" },
{location: "Tuen Mun Road to Ting Kau Bridge", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TC612F.JPG" },
{location: "Wong Chu Road near Lung Mun Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/RT116F.JPG" },
{location: "Wu Chui Road near Wu King Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TM101F.JPG" },
{location: "Yuen Long Highway near Hung Tin Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SW109F.JPG" },
{location: "Yuen Long Highway near Pok Oi Interchange", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SW113F.JPG" },
{location: "Yuen Long Highway near Shap Pat Heung", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SW112F.JPG" },
{location: "Yuen Long Highway near Tan Kwai Tsuen", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SW108F.JPG" },
{location: "Yuen Long Highway near Tong Yan San Tsuen Interchange", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SW111F.JPG" },
{location: "Castle Peak Road near Mai Po", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/BC702F.JPG" },
{location: "Fanling Highway near Hong Lok Yuen Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TP113F.JPG" },
{location: "Fanling Highway near Kwu Tung", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/FH104F.JPG" },
{location: "Fanling Highway near MTR Fanling Station", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/FH706F.JPG" },
{location: "Fanling Highway near Pak Wo Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/FH107F.JPG" },
{location: "Fanling Highway near Sheung Shui Roundabout", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/FH106F.JPG" },
{location: "Jockey Club Road near Fanling Highway", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/NH101F.JPG" },
{location: "Jockey Club Road near Ma Sik Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/NH109F.JPG" },
{location: "Nam Wan Road near Kwong Fuk Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TP114F.JPG" },
{location: "San Sham Road Roundabout", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/BC103F.JPG" },
{location: "San Tin Highway near Fairview Park", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/BC101F.JPG" },
{location: "San Tin Highway near Mai Po", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/BC102F.JPG" },
{location: "San Wan Road near Lung Sum Avenue", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/NH113F.JPG" },
{location: "Sha Tau Kok Road near Ma Sik Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/NH115F.JPG" },
{location: "Tai Lam Tunnel - Yuen Long Side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TL102F.JPG" },
{location: "Tai Lam Tunnel - Ting Kau Side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TL103F.JPG" },
{location: "Tai Po Tai Wo Road near Nam Wan Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TP105F.JPG" },
{location: "Tai Po Tai Wo Road near Tai Po Road- Tai Wo", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TP112F.JPG" },
{location: "Tsing Long Highway near Ko Po San Tsuen", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TL101F.JPG" },
{location: "Yuen Shin Road near Ting Kok Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TP102F.JPG" },
{location: "Fo Tan Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST115F.JPG" },
{location: "Lion Rock Tunnel Road near Hung Mui Kuk Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST922F.JPG" },
{location: "Lion Rock Tunnel Road near Sun Tin Wai Estate", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST725F.JPG" },
{location: "Ma On Shan Bypass near Heng On Estate", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST731F.JPG" },
{location: "Ma On Shan Bypass near Yiu On Estate", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST732F.JPG" },
{location: "Mei Tin Road near Che Kung Miu Road Roundabout", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST112F.JPG" },
{location: "Sai Sha Road near Ma On Shan Sports Ground", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST117F.JPG" },
{location: "Sai Sha Road/Kam Ying Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST119F.JPG" },
{location: "Sha Lek Highway near Prince Wales Hospital", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST715F.JPG" },
{location: "Sha Tin Heights Tunnel - Sha Tin Side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TS105F.JPG" },
{location: "Sha Tin Wai Road/Sha Lek Highway Slip Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST106F.JPG" },
{location: "Shatin Road near Yuen Chau Kok Park", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST721F.JPG" },
{location: "Shing Mun Tunnel Road", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SM933F.JPG" },
{location: "Shing Mun Tunnel Shatin Side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/SM934F.JPG" },
{location: "Tai Chung Kiu Road near Ravana Garden", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST109F.JPG" },
{location: "Tai Po Road - Shatin Section", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST114F.JPG" },
{location: "Tai Po Road near MTR Racecourse Station", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST703F.JPG" },
{location: "Tate's Cairn Highway near Shatin Hospital", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST712F1.JPG" },
{location: "Tate's Cairn Highway near Tai Shek Kwu", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST714F.JPG" },
{location: "Tate's Cairn Tunnel Shatin Side", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST942F.JPG" },
{location: "Tolo Highway near HK Science Park", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TH110F.JPG" },
{location: "Tolo Highway near Island House Interchange", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TH114F.JPG" },
{location: "Tolo Highway near Ma Liu Shui Interchange", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TH101F.JPG" },
{location: "Tolo Highway near Sha Tin Sewage Treatment Works", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/ST701F.JPG" },
{location: "Kap Shui Mun Bridge", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TC551F.JPG" },
{location: "Lantau Link near Toll Plaza", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TC573F.JPG" },
{location: "North Lantau Highway near Pak Mong", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/NL126F.JPG" },
{location: "North Lantau Highway near Siu Ho Wan", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/NL124F.JPG" },
{location: "North Lantau Highway near Sunny Bay", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/NL121F.JPG" },
{location: "North Lantau Highway near Tung Chung", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/NL128F.JPG" },
{location: "Penny's Bay Highway", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/PB106F.JPG" },
{location: "Tsing Ma Bridge", latitude: nil, longitude: nil, uri: "http://tdcctv.data.one.gov.hk/TC560F.JPG" }
])